#version 450
#extension GL_ARB_shading_language_420pack : enable

layout (set = 0, binding = 0) uniform UBO {
	float dt;
} ubo;

struct Particle {
	vec4 position;
	vec4 velocity;
};
layout(set = 1, binding = 0) buffer Storage {
   Particle particles[];
} storage;

layout (local_size_x = 256) in;

void main()  {
	int index = int(gl_GlobalInvocationID);
	storage.particles[index].position += ubo.dt * storage.particles[index].velocity;
}