if(WIN32)
    set(CPP_FLAGS ${MSVC_FLAGS})
    set(VULKAN_LIB "$ENV{VULKAN_SDK}/Lib/vulkan-1.lib")
    set(PLATFORM_LIB "")
else()
    if(CMAKE_BUILD_TYPE MATCHES Debug)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++17 -v")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O2 -std=c++17 -v")
    endif()

    set(CPP_FLAGS ${LLVM_FLAGS})
    set(VULKAN_LIB "$ENV{VULKAN_SDK}/lib/libvulkan.so")
    set(PLATFORM_LIB "stdc++fs")
endif()
